app/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_url'),
    path('about/', views.AboutView.as_view(), name='about_url'),
    path('our-team/', views.TeamView.as_view(), name='team_url'),
    path('awards/', views.AwardsView.as_view(), name='awards_url'),
    path('arenda/', views.ArendaView.as_view(), name='arenda_url'),
    path('sale/', views.SaleView.as_view(), name='sale_url'),
    path('sale/<slug:category_slug>/', views.SaleByCategoryView.as_view(), name='sale_list_by_category'),
    path('portfolio/', views.PortfolioView.as_view(), name='portfolio_url'),
    path('service/', views.ServiceView.as_view(), name='service_url'),
    path('contact/', views.ContactView.as_view(), name='contact_url'),
    path('sale/<int:pk>', views.SaleDetailView.as_view(), name='sale_detail_url'),
]

app/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/templates/include/footer.html
{% load static %}

<!-- footer begin -->
    <footer>
            <div class="container">
                <div class="nav">
                    <div class="col-md-3">
                        <div class="widget widget_recent_post">
                            <h3>О нас</h3>
                            <ul>
                                <li><a href="{% url 'main:about_url' %}">О компании</a></li>
                                <li><a href="{% url 'main:portfolio_url' %}">Портфолио</a></li>
                                <li><a href="{% url 'main:contact_url' %}">Контакты</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="widget widget_recent_post">
                            <h3>Услуги</h3>
                            <ul>
                                <li><a href="{% url 'main:arenda_url' %}">Аренда</a></li>
                                <li><a href="{% url 'main:sale_url' %}">Продажа</a></li>
                                <li><a href="{% url 'main:service_url' %}">Сервис</a></li>
                            </ul>
                        </div>
                    </div>


                    <div class="col-md-5">
                        <div class="widget widget-address" style="margin-top: -16px;">
                            <address>
                                <span class="custom_span"><strong><i class="fa fa-map fa-lg"></i></strong><a href="#">{{ settings.address }}</a></span>
                                <span class="custom_span"><strong><i class="fa fa-phone fa-lg"></i></strong>{{ settings.tel_first }}</span>
                                <span class="custom_span"><strong><i class="fa fa-mobile fa-lg"></i></strong>{{ settings.tel_second }}</span>
                                <span class="custom_span"><strong><i class="fa fa-mail-reply fa-lg"></i></strong><a href="#">{{ settings.email }}</a></span>
                            </address>
                        </div>
                    </div>

                    <div class="col-md-1">
                        <div class="widget widget_recent_post social corr-social" style="margin-top: 5px;">
{#                            <h3>Соцсетях</h3>#}
                            <ul>
                                <li><a href="{{ settings.facebook }}"><i class="fa fa-facebook fa-lg"></i></a></li>
                                <li><a href="{{ settings.instagram }}"><i class="fa fa-instagram fa-lg"></i></a></li>
                                <li><a href="{{ settings.telegram }}"><i class="fa fa-telegram fa-lg"></i></a></li>
                                <li><a href="{{ settings.youtube }}"><i class="fa fa-youtube fa-lg"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
                </div>
            </div>

            <div class="subfooter">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            &copy; Copyright 2017-2021 <span class="id-color">LED DESIGN GROUP</span>
                        </div>
{#                        <div class="col-md-6 text-right">#}
{#                            <div class="social-icons">#}
{#                                <a href="#"><i class="fa fa-facebook fa-lg"></i></a>#}
{#                                <a href="#"><i class="fa fa-twitter fa-lg"></i></a>#}
{#                                <a href="#"><i class="fa fa-telegram fa-lg"></i></a>#}
{#                                <a href="#"><i class="fa fa-instagram fa-lg"></i></a>#}
{#                            </div>#}
{#                        </div>#}
                    </div>
                </div>
            </div>
            <a href="#" id="back-to-top"></a>
        </footer>
<!-- footer close -->

app/templates/include/header.html
{% load static %}
<!-- header begin -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- logo begin -->
                <div id="logo">
                    <a href="{% url 'main:home_url' %}">
                        <img class="logo logo_custom" src="{% static 'images/ldg_logo.png' %}" alt="">
                    </a>
                </div>
                <!-- logo close -->

                <!-- small button begin -->
                <span id="menu-btn"></span>
                <!-- small button close -->

                <!-- mainmenu begin -->
                <nav>
                    <ul id="mainmenu">
                        <li><a href="{% url 'main:home_url' %}">Главная<span></span></a></li>
                        <li><a href="{% url 'main:about_url' %}">О нас </a>
                            <ul>
                                <li><a href="{% url 'main:about_url' %}">О компании</a></li>

                                <li><a href="{% url 'main:team_url' %}">Наша команда</a></li>

                                <li><a href="{% url 'main:awards_url' %}">Сертификаты</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'main:arenda_url' %}">Аренда</a></li>
                        <li><a href="{% url 'main:sale_url' %}">Продажа</a>
                            <ul>
                                {% for item in categories %}
                                    <li><a href="{% url 'main:sale_list_by_category' item.slug %}">{{ item.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li><a href="{% url 'main:service_url' %}" class="menu-items-border">Сервис</a></li>
                        <li><a href="{% url 'main:portfolio_url' %}" class="menu-items-border">Портфолио</a></li>
                        <li><a href="{% url 'main:contact_url' %}" class="menu-items-border">Контакты</a></li>
                        <li>
                            <a href="tel:+998998680002">
                                <div class="tel-border" style="border:1px solid white; padding:  0px 10px; border-radius: 10px;font-size: 15px;"><i class="fa fa-phone fa-lg"></i> +99899 868 00 02</div>
                            </a>
                        </li>
                    </ul>
                </nav>

                <!-- mainmenu close -->

            </div>


        </div>
    </div>
</header>
<!-- header close -->