app/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_url'),
    path('about/', views.AboutView.as_view(), name='about_url'),
    path('our-team/', views.TeamView.as_view(), name='team_url'),
    path('awards/', views.AwardsView.as_view(), name='awards_url'),
    path('arenda/', views.ArendaView.as_view(), name='arenda_url'),
    path('sale/', views.SaleView.as_view(), name='sale_url'),
    path('sale/<slug:category_slug>/', views.SaleByCategoryView.as_view(), name='sale_list_by_category'),
    path('portfolio/', views.PortfolioView.as_view(), name='portfolio_url'),
    path('service/', views.ServiceView.as_view(), name='service_url'),
    path('contact/', views.ContactView.as_view(), name='contact_url'),
    path('sale/<int:pk>', views.SaleDetailView.as_view(), name='sale_detail_url'),
]

app/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/templates/pages/arenda.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Аренда | LED DESIGN GROUP {% endblock title %}

{% block content%}
    <!-- subheader -->
        <section  class="subheader header_arenda_bj" data-speed="8" data-type="background">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 subheader_div">
                        <h1>Аренда</h1>
                    </div>
                </div>
            </div>
        </section>
    <!-- subheader close -->

<!-- content begin -->
        <div id="content" class="no-bottom no-top">

            <!-- revolution slider begin -->
            <section id="section-welcome-14">

				<div class="container">
            {% for arenda in arendas %}

					<div class="row align-items-center no-gutters wow fadeInUp">

                        <div class="col-md-6 text-middle">
							<div class="twentytwenty-container">
							  <img src="{{ arenda.image.url }}" alt="" class="img-responsive" />
							</div>
						</div>

						<div class="col-md-6 text-middle">
							<div class="padding50">
								<h3 class="team-item-title"><span class="id-color">{{ arenda.title }}</span></h3>
								<p class="team-item-text">{{ arenda.description|safe }}</p>
{#								<a href="index-before-after.html#" class="btn-line">View Details</a>#}
							</div>
						</div>

                    </div>
                <div class="spacer-double"></div>

                {% endfor %}

                    <div class="text-center">
                        {% if is_paginated %}
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                                {% endif %}

                            {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                <li class="active"><a>{{ i }}</a></li>
                                        {% else %}
                                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                            {% endfor %}
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                {% endif %}
                            </ul>
                        {% endif %}
                    </div>
				</div>


            </section>
            <!-- revolution slider close -->


			</div>

{% endblock content %}

app/templates/pages/contact.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Контакты | LED DESIGN GROUP {% endblock title %}

{% block content %}

    <!-- subheader -->
    <section class="subheader header_contact_bj" data-speed="8" data-type="background">
        <div class="container">
            <div class="row">
                <div class="col-md-12 subheader_div">
                    <h1>Контакты</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- subheader close -->

    <!-- content begin -->
    <div id="content" class="no-top">
        <section id="de-map" aria-label="map-container">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="map-container map-fullwidth img-rounded">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2997.3935322132684!2d69.21055711481942!3d41.30030180935328!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8ba899063367%3A0x3004bbba7ab68f50!2sLed%20Design%20Group!5e0!3m2!1suz!2s!4v1611468907670!5m2!1suz!2s"
                                    width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""
                                    aria-hidden="false" tabindex="0"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="container">
            <div class="row">

                <div class="col-md-8">
                    <h3>Отправить Сообщение</h3>

                    <form name="contactForm" id='contact_form' method="post" action="{% url 'main:contact_url' %} ">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">

                                {% for error in form.name.errors %}
                                    <div id='name_error' class='error'>{{ error }}</div>
                                {% endfor %}

                                <div>
                                    {{ form.name }}
                                </div>

                                {% for error in form.email.errors %}
                                    <div id="email_error" class='error'>{{ error }}</div>
                                {% endfor %}

                                <div>
                                    {{ form.email }}
                                </div>

                                {% for error in form.phone.errors %}
                                    <div class='error'>{{ error }}</div>
                                {% endfor %}

                                <div>
                                    {{ form.phone }}
                                </div>

                            </div>

                            <div class="col-md-6">

                                {% for error in form.message.errors %}
                                    <div id='message_error' class='error'>{{ error }}</div>
                                {% endfor %}

                                <div>
                                    {{ form.message }}
                                </div>

                            </div>

                            <div class="col-md-12">
                                <button type="submit" class="btn btn-line">Отправить</button>
                                {#                                    <p id='submit'>#}
                                {#                                        <button type='submit' id='send_message' class="btn btn-line">Отправитъ</button>#}
                                {#                                    </p>#}
                                <div id='mail_success' class='success'>Your message has been sent successfully.</div>
                                <div id='mail_fail' class='error'>Sorry, error occured this time sending your message.
                                </div>
                            </div>
                        </div>
                    </form>

                </div>

                <div id="sidebar" class="col-md-4">

                    <div class="widget widget_text">
                        <h3>Контактная Информация</h3>
                        <address>
                            <span class="custom_span"><strong><i class="fa fa-map fa-lg"></i></strong>{{ settings.address }}</span>
                            <span class="custom_span"><strong><i class="fa fa-phone fa-lg"></i></strong>{{ settings.tel_first }}</span>
                            <span class="custom_span"><strong><i class="fa fa-mobile fa-lg"></i></strong><a
                                    href="#">{{ settings.tel_second }}</a></span>
                            <span class="custom_span"><strong><i class="fa fa-mail-reply fa-lg"></i></strong><a
                                    href="#">{{ settings.email }}</a></span>
                            {#                                <span><strong><i class="fa fa-fax fa-lg"></i></strong>{{ settings.fax }}</span>#}
                        </address>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

app/templates/pages/portfolio.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Портфолио | LED DESIGN GROUP {% endblock title %}


{% block content %}
<!-- subheader -->
        <section class="subheader header_portfolio_bj" data-speed="8" data-type="background">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 subheader_div">
                        <h1 class="subheader_title">Портфолио</h1>
                    </div>
                </div>
            </div>
        </section>
<!-- subheader close -->


<!-- section begin -->
    <section id="section-portfolio" class="no-top no-bottom" aria-label="section-portfolio">
                <div class="container">
{#                    <div class="row" style="padding-bottom: 10px; padding-top: 40px">#}
{#                        <div class="col-md-6 offset-md-3 text-center wow fadeInUp">#}
{#                            <h1>Портфолио</h1>#}
{#                            <div class="separator"><span><i class="fa fa-circle"></i></span></div>#}
{#                        </div>#}
{#                </div>#}


                    <div class="spacer-single"></div>

                    <!-- portfolio filter begin -->
{#                    <div class="row">#}
{#                        <div class="col-md-12 text-center">#}
{#                            <ul id="filters" class="wow fadeInUp" data-wow-delay="0s">#}
{#                                <li><a href="index.html#" data-filter="*" class="selected">All Projects</a></li>#}
{#                                <li><a href="index.html#" data-filter=".residential">Residential</a></li>#}
{#                            </ul>#}
{##}
{#                        </div>#}
{#                    </div>#}
                    <!-- portfolio filter close -->

                </div>

                <div id="gallery" class="gallery full-gallery de-gallery pf_full_width wow fadeInUp" data-wow-delay=".3s">

                    {% for portfolio in portfolies %}
                    <!-- gallery item -->
                    <div class="item">
                        <div class="picframe">
                            <a data-fancybox="gallery" href="{{ portfolio.image.url }}">
                                <span class="overlay">
                                    <span class="pf_text">
                                        <span class="project-name">{{ portfolio.title}}</span>
                                    </span>
                                </span>
                            </a>
                            <img src="{{ portfolio.image.url }}" alt="{{ portfolio.title }}" />
                        </div>
                    </div>
                    <!-- close gallery item -->
                {% endfor %}

                </div>

                <div id="loader-area">
                    <div class="project-load"></div>
                </div>
            </section>
<!-- section close -->


{% endblock content %}}

app/templates/pages/sale.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Продажа | LED DESIGN GROUP {% endblock title %}


{% block content %}
    <!-- subheader -->
    <section class="subheader header_sale_bj" data-speed="8" data-type="background">
        <div class="container">
            <div class="row">
                <div class="col-md-12 subheader_div">
                    <h1 class="subheader_title">Продажа</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- subheader close -->


    <!-- content begin -->
    <div id="content" class="no-bottom no-top">

        <!-- revolution slider begin -->
        <section id="section-welcome-14">

            <div class="container">
                <div class="row">

                    {% for item in products %}
                        <div class="col-md-6 col-sm-12 align-items-center no-gutters wow fadeInUp">
                            <div class="item-block-new">

                                <div class="twentytwenty-container new_style_page">
                                    <a href="{% url 'main:sale_detail_url' item.pk %}" class="img-link" style="border: none ">
                                        <img src="{{ item.image.url }}" alt="" class="img-responsive"/>
                                    </a>
                                </div>

                                <div class="padding30 new_block_text">
                                    <h3><span class="id-color sale-item-title bx-color">{{ item.title }}</span></h3>
                                    <p>{{ item.description|safe }}</p>
                                    <a href="{% url 'main:sale_detail_url' item.pk %}" class="btn-line">Подробнее</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="spacer-double"></div>

            </div>


        </section>
        <!-- revolution slider close -->


    </div>

{% endblock content %}

app/templates/pages/sale_by_category.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Продажа | LED DESIGN GROUP {% endblock title %}


{% block content %}
    <!-- subheader -->
    <section class="subheader header_sale_bj" data-speed="8" data-type="background">
        <div class="container">
            <div class="row">
                <div class="col-md-12 subheader_div">
                    <h1 class="subheader_title">Продажа</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- subheader close -->


    <!-- content begin -->
    <div id="content" class="no-bottom no-top">

        <!-- revolution slider begin -->
        <section id="section-welcome-14">

            <div class="container">
                <div class="row">

                    {% for item in products %}
                        <div class="col-md-6 col-sm-12 align-items-center no-gutters wow fadeInUp">
                            <div class="item-block-new">

                                <div class="twentytwenty-container new_style_page">
                                    <a href="{% url 'main:sale_detail_url' item.pk %}" class="img-link" style="border: none ">
                                        <img src="{{ item.image.url }}" alt="" class="img-responsive"/>
                                    </a>
                                </div>

                                <div class="padding30 new_block_text">
                                    <h3><span class="id-color sale-item-title bx-color">{{ item.title }}</span></h3>
                                    <p>{{ item.description|safe }}</p>
                                    <a href="{% url 'main:sale_detail_url' item.pk %}" class="btn-line">Подробнее</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <div class="spacer-double"></div>

            </div>


        </section>
        <!-- revolution slider close -->


    </div>

{% endblock content %}

app/templates/pages/sale_datail.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    <!-- parallax section -->
    <section id="section-welcome" data-bgimage="url({% static 'images/background/detail_prodaja.jpg' %})"
             class="relative full-height overflow-hidden" data-stellar-background-ratio=".5">
        <div id="particles-js"></div>

        <div class="center-y relative text-center pt-lg-5 sale-detail-page">

            <div class="spacer-double"></div>
            <img src="{{ object.image_inner.url }}" class="img-fluid">
            <div class="spacer-single"></div>
            <h2>{{ object.title }}</h2>
        </div>


    </section>
    <!-- parallax section close -->


<div class="container">
        <div class="row mb-5 sale-deail-table" style="margin-top: -10px;">
        <div class="col-lg-6 col-md-12 col-sm-12 p-5">
            <div class="owl-carousel owl-product owl-theme">
                {% for i in object.slider_image.all %}
                    <div class="item"><img src="{{ i.image.url }}"></div>
                {% endfor %}

            </div>
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12 sale-table-borders">
             <p>{{ object.content|safe }}</p>
        </div>
    </div>
</div>



{% endblock content %}
{% block js %}
    <script src="{% static 'js/particles.js' %}"></script>
    <script src="{% static 'js/particles-settings.js' %}"></script>
{% endblock js %}

app/templates/pages/service.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Сервисы | LED DESIGN GROUP {% endblock title %}


{% block content %}

    <!-- subheader -->
    <section class="subheader header_service_bj" data-speed="8" data-type="background">
        <div class="container">
            <div class="row">
                <div class="col-md-12 subheader_div">
                    <h1>Сервисы</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- subheader close -->
    <!-- section begin -->
    <section id="section-welcome-14" class="no-top no-bottom sm-mt0 ">

        <div class="container corr-services">

            {% for service in services %}
                {% if forloop.counter|divisibleby:2 %}
                    <div class="row align-items-center no-gutters wow fadeInUp" data-bgcolor="rgba(20,20,20,.9)">

                        <div class="col-md-6 text-middle">
                            <div class="twentytwenty-container">
                                <img src="{{ service.image.url }}" alt="" class="img-responsive"/>
                            </div>
                        </div>

                        <div class="col-md-6 text-middle">
                            <div class="padding50">
                                <h3><span>{{ service.title }}</span></h3>
{#                                <h3><span class="id-color">{{ service.title }}</span></h3>#}
                                <p>{{ service.description|safe }}</p>
                            </div>
                        </div>

                    </div>
                {% else %}
                    <div class="row align-items-center no-gutters wow fadeInUp" data-bgcolor="rgba(20,20,20,.9)">
                        <div class="col-md-6 text-middle">
                            <div class="padding50">
                                <h3><span>{{ service.title }}</span></h3>
                                <p>{{ service.description|safe }}</p>
                                <a href="{% url 'main:arenda_url' %}" class="btn-line btn-line-custom">Подробнее</a>
                            </div>
                        </div>

                        <div class="col-md-6 text-middle">
                            <div class="twentytwenty-container">
                                <img src="{{ service.image.url }}" alt="" class="img-responsive"/>
                            </div>
                        </div>

                    </div>
                {% endif %}
            {% endfor %}


        </div>

    </section>
    <!-- section close -->
{% endblock content %}